### ISSUE TITLE
gcc46 : No such file or directory

### ISSUE THREAD

**Issue by MuLx10** [zoq/nes#2]
```
[ 16%] Building CXX object CMakeFiles/balancer.dir/balancer.cpp.o
c++: error: unrecognized command line option ‘-Wl’; did you mean ‘-W’?
c++: error: unrecognized command line option ‘-rpath’
CMakeFiles/balancer.dir/build.make:62: recipe for target 'CMakeFiles/balancer.dir/balancer.cpp.o' failed
```
I have installed the dependencies listed in README.md, still unable to `make`.

**Comment by zoq** [comment]
Can you remove ``-fPIC -Wl -rpath /usr/local/lib/gcc46`` from

https://github.com/zoq/nes/blob/c64886618939589e980695a44f141a01b99f406f/CMakeLists.txt#L10

and test again?

**Comment by MuLx10** [comment]
@zoq  it is working now, thanks

**Comment by zoq** [comment]
Great, fixed in: https://github.com/zoq/nes/commit/ba622e134db0548ebbc9bd2c5c3d587b348f6ab8.
